### ISSUE TITLE
Camera problem

### ISSUE THREAD

**Issue by ColeXJ** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#33]
Please forgive me for my poor English, using the translator. The problem with 14.5 v1.3 is that when I use Facetime or other video software, does the camera display a black-and-white flicker? Do you have this question?

**Comment by wu-hongjun** [comment]
Change the input source. You are probably using the IR camera which doesn’t quite work. Personally I don’t use FaceTime so I can’t tell you how to fix it but that is the problem.

**Comment by flymin** [comment]
@ColeXJ If apps from Apple like FaceTime are only apps you use with camera, you can change the source of video input from the "Video" Tab on the top. Normal camera rather than IR camera works well for me. 
BTW, I suffered a lot when I wanted to make video call via WeChat, because there is not such an option for me to choose the video input, and the IR camera seems to be taken as default. So I made a [patch](https://github.com/flymin/Hackintosh-Thinkpad-X1-Extreme/blob/master/10.14.5/1.3/CLOVER/ACPI/dsl/SSDT-UIAC.dsl) to disable the IR camera in the USB config of ACPI, following the instruction in this [issue](https://github.com/kk1987/P52s-hackintosh/issues/2#issuecomment-513992223). Everything seems fine now.

**Comment by wu-hongjun** [comment]
> @ColeXJ If apps from Apple like FaceTime are only apps you use with camera, you can change the source of video input from the "Video" Tab on the top. Normal camera rather than IR camera works well for me.
> BTW, I suffered a lot when I wanted to make video call via WeChat, because there is not such an option for me to choose the video input, and the IR camera seems to be taken as default. So I made a [patch](https://github.com/flymin/Hackintosh-Thinkpad-X1-Extreme/blob/master/10.14.5/1.3/CLOVER/ACPI/dsl/SSDT-UIAC.dsl) to disable the IR camera in the USB config of ACPI, following the instruction in this [issue](https://github.com/kk1987/P52s-hackintosh/issues/2#issuecomment-513992223). Everything seems fine now.

Released [v10.15.0.1.2](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.15.0.1.2), added the ACPI patch to the binaries. Thanks for your contribution!

**Comment by ColeXJ** [comment]
could you update these changes to  14.5 v1.3 please?

**Comment by flymin** [comment]
@ColeXJ The releases are actually compatible with earlier versions. I'm using 14.5 with the newest [v10.15.0.1.2 release](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.15.0.1.2)

**Comment by Errrneist** [comment]
> could you update these changes to 14.5 v1.3 please?

What 14.5 v1.3?

**Comment by wu-hongjun** [comment]
> could you update these changes to 14.5 v1.3 please?

Oh I see. In theory, v10.15.0.1.2 should be downward compatible since it is newer. Since I am no longer on Mojave it is impossible for me to push a Mojave compatible update. You should backup your working EFI with a rescue USB and install the newest build. Hope that helps.
