### ISSUE TITLE
ThinkPad P1 Compatibility

### ISSUE THREAD

**Issue by Invisiblebanana789** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#35]
Hey y'all,

Does anyone here know how well a ThinkPad P1 will work with this hackintosh guide instead of an X1 Extreme? Specifically the Intel Xeon model with a Quadro P2000, if it makes any difference?

I've ordered the wdxxfu adapter and he said the adapter probably should work, but if anyone here has further insight that would be appreciated.

For those wondering, I'm planning to go with the P1 instead of the Extreme because of the ISV Certifications, Xeon, and the lower overall price tag.

And Errrniest, I've read the TonyMac forum and unfortunately cannot provide you one to test :(
lol but in actuality, kudos to you and everyone for making this whole thing possible!

Thanks!

:)

**Comment by Invisiblebanana789** [comment]
BTW For the wdxxfu adapter to work, should I purchase the smart card reader or not?

**Comment by wu-hongjun** [comment]
Nope you need to get rid of the smart card reader if you have one. I think the adapter will work, with little doubt. P1 though you probably need customize a lot of things including definitely patching your DSDT (I think the chipset is a bit different too for Xeon...?), but overall stuff should be similar.

**Comment by Invisiblebanana789** [comment]
Alright, thanks! 

I haven't ordered a P1 just yet - waiting till Cyber Monday for them deals :)

Is it okay if I post issues later relating to the P1, with "P1" in the title to differentiate? 

And finally, is there anything especially difficult to do relating to customizing things for the P1, and what can you think of that may require customization?

Thanks!

-IB

**Comment by wu-hongjun** [comment]
> Alright, thanks!
> 
> I haven't ordered a P1 just yet - waiting till Cyber Monday for them deals :)
> 
> Is it okay if I post issues later relating to the P1, with "P1" in the title to differentiate?
> 
> And finally, is there anything especially difficult to do relating to customizing things for the P1, and what can you think of that may require customization?
> 
> Thanks!
> 
> -IB

You are completely welcomed to post things related to P1, since these two machines have similarities.

I would argue that X1E Gen2 is coming out, that might be a better pick.

(Honestly, mobile Quadro chips does not provide a lot of performance in terms of professional performance. You would be better off using eGPU for Quadro, which is much more cost efficient, powerful, and upgradeable. Not to mention mobile workstations are expensive, unless you really really need Xeon and ECC, or 10bit internal screen. I used P50 before, and I don't spot a huge difference. You can get vPro in consumer chips too, like 8850H.)

The only things you can possibly customize is wifi card, RAM, SSD, and "Smartcard"(SC).

How the express card thing works is we use the USB data channels of SC for BT signals to pass through since the SC slot is essentially a USB2.0 port.

X1E G2 might not have Hackintosh support yet, but if you have to buy something now, you'd better off with a discounted X1E (+Hackintosh since we did a lot research already) or wait for X1E Gen2 for the bang of money.

Hope that helps.

**Comment by wu-hongjun** [comment]
> Alright, thanks!
> 
> I haven't ordered a P1 just yet - waiting till Cyber Monday for them deals :)
> 
> Is it okay if I post issues later relating to the P1, with "P1" in the title to differentiate?
> 
> And finally, is there anything especially difficult to do relating to customizing things for the P1, and what can you think of that may require customization?
> 
> Thanks!
> 
> -IB

Also, since laptop Quadro uses Optimus and NVIDIA isn't supported by macOS at all, whether it is a GeForce or Quadro makes no difference since they won't work, and even if Apple enables NVIDIA support it still would not work because macOS does not support Optimus. 

The 8bit internal 4K HDR screen is extremely good to my eyes (I do content creation a lot, and I don't spot any significant gain even if you upgrade to 10 bit.) 

You don't need ECC unless you need super accurate computation like in the business analyzation or financial computing. 

So yeah, nothing wrong for buying a mobile workstation (Some people, even I used to work in the fields when I needed to use Solidworks and stuff like that so it is useful), but unless your company pays the expense for you, I think P1 is overpriced.

**Comment by Invisiblebanana789** [comment]
Whoa, thanks for the extremely detailed reply!

I plan to use the laptop unplugged for a decent amount of time. Have you experienced any issues with the fans running extremely loud or horrible battery life? And are those issues lessened in Mac OS since there's not a dgpu running?

And right now, iirc, the P1 is actually cheaper than the Extreme on an identical configuration (except for gpu) since Lenovo's experimenting with pricing or something.

Also, do you think a P1 without the workstation hardware is a good choice? (Like Core i7)

I think my laptop choice will probably still be between the P1 and Extreme (gen 1) due to the hackintosh documentation. Out of those, I'll probably just get the best specs I can that fit my budget. 

Thanks for the info about how a P1 probably is overkill. If I can afford it though, I might get it since I'll be using the laptop for 4 years and don't know how intense my computational tasks will be by then.

Right now, on a Lenovo corporate discount site plus coupon codes, a P1 with Xeon, P2000 (which kinda doesn't matter), Win10ProFW, and base ram and ssd is $1535. Do you think the config plus a custom ram/ssd upgrade is a good deal? And if you don't mind sharing, how much was your config?

And finally, do you know whether upgrading the ram and ssd will cause any issues? I'm planning on replacing RAM with Crucial RAM (possibly ecc if it's cheap) and adding in a 970 EVO 1TB for Mac OS, with Windows on the stock ssd.

Thanks for all your help!

-IB

**Comment by gfoury** [comment]
> Also, since laptop Quadro uses Optimus and NVIDIA isn't supported by macOS at all, whether it is a GeForce or Quadro makes no difference since they won't work, and even if Apple enables NVIDIA support it still would not work because macOS does not support Optimus.

Unlike many Optimus laptops, the X1E BIOS allows switching the primary display from integrated to discrete. I expect that if NVIDIA is ever supported, we can throw that switch and run completely on the discrete card.

If I recall correctly, on the X1E the HDMI/DisplayPort outputs are wired to the discrete card--that is, there is no external video on macOS.

**Comment by wu-hongjun** [comment]
> > Also, since laptop Quadro uses Optimus and NVIDIA isn't supported by macOS at all, whether it is a GeForce or Quadro makes no difference since they won't work, and even if Apple enables NVIDIA support it still would not work because macOS does not support Optimus.
> 
> Unlike many Optimus laptops, the X1E BIOS allows switching the primary display from integrated to discrete. I expect that if NVIDIA is ever supported, we can throw that switch and run completely on the discrete card.
> 
> If I recall correctly, on the X1E the HDMI/DisplayPort outputs are wired to the discrete card--that is, there is no external video on macOS.

It will be a significant battery drainer...

**Comment by wu-hongjun** [comment]
> Whoa, thanks for the extremely detailed reply!
> 
> I plan to use the laptop unplugged for a decent amount of time. Have you experienced any issues with the fans running extremely loud or horrible battery life? And are those issues lessened in Mac OS since there's not a dgpu running?
> 
> And right now, iirc, the P1 is actually cheaper than the Extreme on an identical configuration (except for gpu) since Lenovo's experimenting with pricing or something.
> 
> Also, do you think a P1 without the workstation hardware is a good choice? (Like Core i7)
> 
> I think my laptop choice will probably still be between the P1 and Extreme (gen 1) due to the hackintosh documentation. Out of those, I'll probably just get the best specs I can that fit my budget.
> 
> Thanks for the info about how a P1 probably is overkill. If I can afford it though, I might get it since I'll be using the laptop for 4 years and don't know how intense my computational tasks will be by then.
> 
> Right now, on a Lenovo corporate discount site plus coupon codes, a P1 with Xeon, P2000 (which kinda doesn't matter), Win10ProFW, and base ram and ssd is $1535. Do you think the config plus a custom ram/ssd upgrade is a good deal? And if you don't mind sharing, how much was your config?
> 
> And finally, do you know whether upgrading the ram and ssd will cause any issues? I'm planning on replacing RAM with Crucial RAM (possibly ecc if it's cheap) and adding in a 970 EVO 1TB for Mac OS, with Windows on the stock ssd.
> 
> Thanks for all your help!
> 
> -IB

1. Fans actually run MUCH freaking quietly than Windows due to a conservative fan tuning in macOS and no dGPU.

2. IDK maybe the beta version of macOS Catalina drains more battery, or hackintosh just uses more battery, I get around 2:12 on battery using iStats and it is accurate.

3. Yes, Coorporate Perks is the way to go, I bought mine there too.

4. Be careful with SSD, since people have issue PM971 and 970 EVO (If I remember it right) is essentially PM971. See readme.MD for issues. Also, Toshiba XG3 I use is off eBay for a really cheap price (Since it is from OEM) and I've been using it for a long long time now without issue (P50 -> Aero 15 -> X1E Hummm about three years...?)

5. Be careful with RAM if you add it to 64G you might need extra RAM injections. See readme.MD for RAM issues.

6. I bought mine last year october so it is about a year from now, and it cost around $2200 on Coorporate Perks I believe. So it is indeed a good deal.

Hope that helps.

**Comment by Invisiblebanana789** [comment]
Thanks for the info!

For 1: Is the fan tuning inside MacOS or in bios?

For 2: Will there be a guide to fixing the battery life during the next few months?

--

And finally, a completely irrelevant question: Is it possible to set up the hackintosh so that the whole MacOS thing plus Clover (on dual boot w/ windows) is stored on a single ssd drive, where:

1) The drive can be removed temporarily to make the machine a normal Windows laptop

2) There can be a copy of the MacOS drive somewhere else (on another drive, for instance) as a backup so that, in the unlikely event that the current MacOS drive is physically damaged or fails, I can put the copy on another drive and the hackintosh would work identically (sorry if that's worded badly)

And if they're possible, how difficult would they be to set up?

Thanks again!

-IB

**Comment by wu-hongjun** [comment]
> Thanks for the info!
> 
> For #1: Is the fan tuning inside MacOS or in bios?
> 
> For #2: Will there be a guide to fixing the battery life during the next few months?
> 
> --
> 
> And finally, a completely irrelevant question: Is it possible to set up the hackintosh so that the whole MacOS thing plus Clover (on dual boot w/ windows) is stored on a single ssd drive, where:
> 
> 1. The drive can be removed temporarily to make the machine a normal Windows laptop
> 2. There can be a copy of the MacOS drive somewhere else (on another drive, for instance) as a backup so that, in the unlikely event that the current MacOS drive is physically damaged or fails, I can put the copy on another drive and the hackintosh would work immediately, the same way as the previous one (sorry if that's worded badly)
> 
> And if they're possible, how difficult would they be to set up?
> 
> Thanks again!
> 
> -IB

1. It’s the way Apple tune their fan curve in macOS I believe. I didn’t tweak anything to the fan.

2. I don’t know, possible not since I don’t even know what’s the problem. It could also well because the X1E has a 80Wh battery, H series processor, 4K screen in its max brightness,  and 32G of DDR4 which I can see they drain a lot of power given the battery life in Windows is not any better(Apple actually explained once why it used 16G in their rmbp and cannot upgrade to 32G because memory controller for large DDR4 drain a significant amount of power relative to maximum 16G).

For the last question, dual boot is exactly my setup...it is so far the easiest and most secure since if you need to do a reset on your Windows using Lenovo’s one trick recovery tool it will wipe everything in any disk in your computer, so in that case, taking the drive out by screwing off several screws is plausible, not to mention if you mess up your Hackintosh (Which is very possible I did it multiple times during development) a fresh install is easy.

**Comment by Invisiblebanana789** [comment]
Is there anything extra I need to do to set it up that way or do the normal instructions from the ReadMe set it up identically?

Thanks!

-IB

**Comment by wu-hongjun** [comment]
> Is there anything extra I need to do to set it up that way or do the normal instructions from the ReadMe set it up identically?
> 
> Thanks!
> 
> -IB

In theory it should just work as it works with a lot of people, but your mileage might vary since some other people suffer boot time lag and have to patch their own DSDT. Can’t promise anything.

**Comment by Invisiblebanana789** [comment]
Alright!

Thanks for all your help!

-IB

:)

**Comment by gfoury** [comment]
I'm not having problems with a 1TB 970 EVO. ("System Information.app" claims the revision is `2B2QEXE7`, whatever that means.) Here is [what I ordered from Amazon](https://www.amazon.com/gp/product/B07BN217QG) on 2019-01-05.

**Comment by gfoury** [comment]
@Errrneist: 

> It’s the way Apple tune their fan curve in macOS I believe. I didn’t tweak anything to the fan.

Do you have any ideas on how to tune the fan? I'm not happy with it.

**Comment by wu-hongjun** [comment]
> @Errrneist:
> 
> > It’s the way Apple tune their fan curve in macOS I believe. I didn’t tweak anything to the fan.
> 
> Do you have any ideas on how to tune the fan? I'm not happy with it.

Unfortunately I don’t know.

**Comment by wu-hongjun** [comment]
> Alright!
> 
> Thanks for all your help!
> 
> -IB
> 
> :)

Oh, by the way, if you happens to buy a P1, feel free to open up a new Github repo for P1 (Even if mostly using my stuff I don't really care) so people can have access to it :) Tell me and I will reference it in my readme.MD.

**Comment by Invisiblebanana789** [comment]
Cool, I'll try!

It probably won't be ready for a long time and as elaborate as yours, but I'll at least upload the files I used.
(Maybe the p1 and extreme will be obsolete by then since there's already a gen 2 of both, idk)

Thanks again for all your help so far, and I hope I can eventually help others like you have.

-IB


:)

**Comment by ucdavis95616** [comment]
> > Also, since laptop Quadro uses Optimus and NVIDIA isn't supported by macOS at all, whether it is a GeForce or Quadro makes no difference since they won't work, and even if Apple enables NVIDIA support it still would not work because macOS does not support Optimus.
> 
> Unlike many Optimus laptops, the X1E BIOS allows switching the primary display from integrated to discrete. I expect that if NVIDIA is ever supported, we can throw that switch and run completely on the discrete card.
> 
> If I recall correctly, on the X1E the HDMI/DisplayPort outputs are wired to the discrete card--that is, there is no external video on macOS.

Technically yes but practically no. You may destroy your laptop to a birck if bios configuration is not favorable by default since the poor quality assurance of Thinkpad bios is always beyond your imagination.
