### ISSUE TITLE
Bad Performance of UHD 630 (Photoshop, FinalCut and other OpenCL Apps)

### ISSUE THREAD

**Issue by Romsky** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#4]
I followed your guide and the result is almost perfect. All is working as it should. Cardreader, Display, Brightness, Audio, Wireless (no BT of course), Sound, Sleep, Wake etc. I also use undervolt for my device to get less fan activity and better batterylife.

I use the Device for Video and Photoediting. First i wonder about very poor export times in FinalCut, even though GPU is recognized correct and Clocks are good too (checked with Intel Power Gagdet). I have here a MacBook Pro 13,3 2018, with 8259u and Iris 655... almost twice as fast... when i use Photoshop (UHD 630 is recognized again anch checked) and i zoom in in Photo its laggy as hell. (like no acceleration). 

Something is wrong with the UHD 630 Solution we use to get it work in Mojave.

**Comment by wu-hongjun** [comment]
So far, I use Macbook Pro 15,2 in SMBIOS, because 15,2(WHich is 13' model and has Iris Pro) works generally better as a whole. I spent at least a month using 15,1(Which is the 15' model and has UHD530/Radeon) but that did not work well. zysuper presented a solution using 15,2 and it is much more compatiable and it is also suggested by RehabMan. I am not sure what we can do about this at this point of time...

**Comment by zysuper** [comment]
No problem with Macbook Pro 15,2. In testing...

**Comment by wu-hongjun** [comment]
I also don't have any issue with it so far. I am afraid it is just simply Intel making crappy iGPU. Keep in mind that UHD 630 has significantly fewer graphics power than Iris 655 since Iris 655 has twice amount of graphics processor as well as an extra buffer memory. More spec and compare over [here](https://www.notebookcheck.net/Iris-Plus-Graphics-655-vs-UHD-Graphics-630-vs-HD-Graphics-P630_8828_8126_7657.247598.0.html).

**Comment by thanik** [comment]
Sorry to bring this up, my X1 has 8850H and I used this Clover config and found that my CPU always ran at the base clock as the maximum clock (2.60GHz) and it can't go past that clock speed so I did an SSDT XCPM patch in Native Power Management guide in tonymacx86 then I got boosted clock with a better performance.
