### ISSUE TITLE
Hackintosh-Thinkpad-X1-Extreme Gen 2

### ISSUE THREAD

**Issue by dyf102** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#43]
Hi, 

Is there any plan to support the Gen 2?

Thanks

**Comment by Invisiblebanana789** [comment]
Gen 2 isn't as well documented, but the internals are similar thus many things from the Gen 1 guide should apply to the Gen 2. I believe the Wifi Card and optional adapter are supported. You may run into some issues with the newer processor and such. 

Overall, you can probably do it with the Gen 2, but it'll require a bit more tinkering with everything to make it work. (possibly ranging from a few extra hours to a lot more, depending on the problems you encounter).

@Errrneist has the Gen 1 and probably can't release a great Gen 2 tutorial without obtaining a Gen 2 himself since he won't be able to physically test it and troubleshoot the errors. 

If you do decide to try it with the Gen 2, please document it to some extent on github to help out the community, namely those with a Gen 2 as well.

I'm no expert on this by any means, so take this with a grain of salt.
​
​
​
​
​
​
​
​
​
​
​
​
​
glhf

**Comment by wu-hongjun** [comment]
> Hi,
> 
> Is there any plan to support the Gen 2?
> 
> Thanks

Yeah can’t do anything unless I get a gen2.

**Comment by Jamesxxx1997** [comment]
Here is a full hotpatch efi , you can give it a try https://github.com/Jamesxxx1997/thinkpad-x1-extreme-gen-2-hackintosh
The USB port might still have issue , for the person who make this efi don't have this machine.

**Comment by ghost** [comment]
Huh? It's just a README file at that link

**Comment by Jamesxxx1997** [comment]
> Huh? It's just a README file at that link

🤣🤣🤣🤣🤣 my fault.
Will reupload the file tonight

**Comment by miyoyo** [comment]
@Jamesxxx1997 I don't know if I should post here or in your repo, so I'll just try here.
Your configuration _does not work_ on my device, it always has issues with the boot process pausing at `Resetting IOCatalogue` and requires injecting the Intel GPU to work properly

This repo **does** work (10.14.5/1.3) with the Intel GPU injection and deleting the DSDT however.

I have a 1080p i7-9750H with a 1650 and 32GB of RAM if that matters.

**Comment by wu-hongjun** [comment]
> @Jamesxxx1997 I don't know if I should post here or in your repo, so I'll just try here.
> Your configuration _does not work_ on my device, it always has issues with the boot process pausing at `Resetting IOCatalogue` and requires injecting the Intel GPU to work properly
> 
> This repo **does** work (10.14.5/1.3) with the Intel GPU injection and deleting the DSDT however.
> 
> I have a 1080p i7-9750H with a 1650 and 32GB of RAM if that matters.

Hummm maybe it's better just to post in his repo? Can't help with 1650...
