### ISSUE TITLE
TouchScreen Multitouch

### ISSUE THREAD

**Issue by liuyishengalan** [Errrneist/Hackintosh-Thinkpad-X1-Extreme#56]
I heard that the touchscreen of X1E works well. I am interested in how you make the touchscreen work well under Catalina. I have a P52, also have a USB  Wacom controller, however, the touch was totally dead as system updated to 10.15. By the way, the touchscreen used to support one finger-touch in Mojave. Any suggestions for solving this problem?

刚刚从一个对触摸很热衷的x1yoga3的用户那得知您那边的x1e触摸在catalina下支持了多点触摸。刚刚也看了您的预览视频，真的很棒。我是Thinkpad p52 机型，触摸面板也是wacom usb协议的。很好奇您的设备是如何工作中的，希望得到相关建议。

**Comment by liuyishengalan** [comment]
如果方便使用qq的话，我们建立了一个qq群（P系列T系列和X系列黑苹果），群里也有x1e用户。
群号“97986046”
来讨论一下触摸屏的解决方案

**Comment by wu-hongjun** [comment]
> 如果方便使用qq的话，我们建立了一个qq群（P系列T系列和X系列黑苹果），群里也有x1e用户。
> 群号“97986046”
> 来讨论一下触摸屏的解决方案

学业繁忙 懒得加了 有问题读readme啊都在里面我写了那么多

**Comment by wu-hongjun** [comment]
Touchpad, Touchscreen and Multi-Gesture:
**Turns out Acidanthera's VoodooPS2Controller.kext is good enough for enabling multigesture and touchscreen.**

No need for VoodooI2C.kext! (Change merged in the 10.15.0.3.2 release)
I was requested to make a video on how it works on the touch screen, link below.

Touch screen gesture implementation on X1E, Errrneist, 2019.
VoodooI2C.kext:

NOTE: I used to say VoodooI2C is not working and unuseful, I was wrong. It works to enable gesture on the touch display.
A interesting discussion with jamesxxx1997 implies that (At least on 10.14) you can use VoodooI2C.kext to achieve touch screen and touchpad gesture support.
Optional Reading: A more through guide for VoodooI2C is here: Guide(Chinese).
